import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import arrayShuffle from 'array-shuffle'
import { useState } from 'react'
import { Container, Row, Col, Button } from 'react-bootstrap'

const characters = [
  'goku-SS',
  'vegeta-SS',
  'trunks',
  'gohan-y',
  'freeza',
  'majinBoo-z',
  'cell',
  'kuririn',
  'piccolo',
  'no16',
  'no18',
  'gokuSsgss',
  'vegetaSsgss',
  'yamcha',
  'tenshinhan',
  'nappa',
  'ginyu',
  'gotenks',
  'gohan',
  'majinBoo',
  'beerus',
  'hit',
  'gokubl',
  'no21',
  'barduck',
  'broly',
  'zamasu',
  'vegetto',
  'goku',
  'vegeta',
  'cooler',
  'no17',
  'jiren',
  'videl',
  'goku-gt',
  'janemba',
  'gogeta',
  'broly-dbs',
  'kefla',
  'goku-ui',
  'masterroshi',
  'superbaby2',
  'gogetaSS4',
]

export default function Home() {
  const [shuffled, setShuffled] = useState(arrayShuffle(characters))
  // const shuffled = arrayShuffle(characters)

  const renderShuffled = (start, end) =>
    shuffled
      .slice(start, end)
      .map((c) => (
        <img
          className="mt-1"
          key={c}
          src={`https://dba.bn-ent.net/character/images/select_${c}_off.png`}
        />
      ))
  // console.log(shuffled.slice(0, 3))
  return (
    <Container className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {characters.map((i) => (
        <img
          key={`chached${i}`}
          src={`https://dba.bn-ent.net/character/images/select_${i}_off.png`}
          className="d-none"
        />
      ))}
      <main className={styles.main}>
        <Row>
          <Col>
            <img src="https://dbfz.bn-ent.net/images/common/logo_dbfz.png" className={styles.logoImg} />
          </Col>
        </Row>
        <Row>
          <Col className={styles.characters}>{renderShuffled(0, 3)}</Col>
        </Row>
        <img src="/vs.png" />
        <Row>
          <Col className={styles.characters}>{renderShuffled(4, 7)}</Col>
        </Row>
        <button
          className={styles.button}
          size="lg"
          onClick={() => setShuffled(arrayShuffle(characters))}
        >
          Shuffle
        </button>
      </main>
      <footer className={styles.footer}>
        <a
          href="https://github.com/fabian202"
          target="_blank"
          rel="noopener noreferrer"
        >
          By fabian202{' '}
          <span className={styles.logo}>
            <img
              src="https://github.com/fabian202.png?size=40"
              alt="Vercel Logo"
            />
          </span>
        </a>
      </footer>
    </Container>
  )
}
